const fs = require('fs');

const url = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL || 'YOUR_SUPABASE_PROJECT_URL';
const anonKey = process.env.SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY || 'YOUR_SUPABASE_ANON_KEY';

const configContent = `// Automatically generated by build-config.js during Vercel deployment
window.SUPABASE_CONFIG = {
    url: "${url}",
    anonKey: "${anonKey}"
};
`;

fs.writeFileSync('supabase-config.js', configContent);
console.log('supabase-config.js successfully generated.');

// ── 캐시버스팅: app.js 버전 파라미터를 커밋 해시(또는 타임스탬프)로 자동 갱신 ──
const buildVersion = process.env.VERCEL_GIT_COMMIT_SHA
    ? process.env.VERCEL_GIT_COMMIT_SHA.slice(0, 7)
    : Date.now().toString(36);

let html = fs.readFileSync('index.html', 'utf-8');
html = html.replace(/app\.js\?v=[^"']+/, `app.js?v=${buildVersion}`);
fs.writeFileSync('index.html', html);
console.log(`app.js cache-busting version updated to: ${buildVersion}`);
