const fs = require('fs');

const url = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL || 'YOUR_SUPABASE_PROJECT_URL';
const anonKey = process.env.SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY || 'YOUR_SUPABASE_ANON_KEY';

const configContent = `// Automatically generated by build-config.js during Vercel deployment
window.SUPABASE_CONFIG = {
    url: "${url}",
    anonKey: "${anonKey}"
};
`;

fs.writeFileSync('supabase-config.js', configContent);
console.log('supabase-config.js successfully generated.');
