-- V16 — 0029 §B: 테일러링 표준 트리 시드 (테일러링 가이드 v2.0에서 생성 — generate_v16_seed.py)
-- 수기 편집 금지: 재생성으로 갱신한다. 기존 데모 트리(methodology NULL)는 유지.

-- ===== OPMS (01.OPMS(사업관리)) =====
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, description, methodology, sort_order) VALUES (NULL, 'PHASE', 'PRR', '사업준비 (Project Preparation)', NULL, 'OPMS', 10);
SET @ph := LAST_INSERT_ID();
SET @p_OPMS_PRR := @ph;
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_OPMS_PRR, 'ACTIVITY', 'PRR-OP', '사업발주 준비', 'OPMS', 10);
SET @a_OPMS_PRR_OP := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PRR_OP, 'TASK', 'PRR-OP-1', '사업계획지원', 'OPMS', 10);
SET @t_OPMS_PRR_OP_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRR_OP_1, 'DELIVERABLE', 'PRR-OP-110', '사업계획서', 'OPMS', 10, 1, 0, 0, 0, '.hwpx', '사업계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRR_OP_1, 'DELIVERABLE', 'PRR-OP-120', '산출내역서', 'OPMS', 20, 1, 0, 0, 0, '.hwpx', '산출내역서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PRR_OP, 'TASK', 'PRR-OP-2', 'RFP지원', 'OPMS', 30);
SET @t_OPMS_PRR_OP_2 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRR_OP_2, 'DELIVERABLE', 'PRR-OP-210', '제안공고서', 'OPMS', 30, 1, 0, 0, 0, '.hwpx', '공고서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRR_OP_2, 'DELIVERABLE', 'PRR-OP-240', '제안요청서', 'OPMS', 40, 0, 1, 1, 1, '.hwpx', '제안요청서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_OPMS_PRR, 'ACTIVITY', 'PRR-PW', '제안작업', 'OPMS', 50);
SET @a_OPMS_PRR_PW := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PRR_PW, 'TASK', 'PRR-PW-1', '제안서작성', 'OPMS', 50);
SET @t_OPMS_PRR_PW_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRR_PW_1, 'DELIVERABLE', 'PRR-PW-110', '제안서', 'OPMS', 50, 0, 1, 1, 1, '.pptx', '제안서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRR_PW_1, 'DELIVERABLE', 'PRR-PW-120', '발표자료', 'OPMS', 60, 0, 0, 1, 1, '.pptx', '발표자료');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PRR_PW, 'TASK', 'PRR-PW-2', '제안발표', 'OPMS', 70);
SET @t_OPMS_PRR_PW_2 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRR_PW_2, 'DELIVERABLE', 'PRR-PW-210', '예상질문서', 'OPMS', 70, 0, 0, 1, 1, '.pptx', '예상질의서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, description, methodology, sort_order) VALUES (NULL, 'PHASE', 'PRP', '착수계획', NULL, 'OPMS', 80);
SET @ph := LAST_INSERT_ID();
SET @p_OPMS_PRP := @ph;
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_OPMS_PRP, 'ACTIVITY', 'PRP-CT', '계약', 'OPMS', 80);
SET @a_OPMS_PRP_CT := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PRP_CT, 'TASK', 'PRP-CT-1', '계약체결', 'OPMS', 80);
SET @t_OPMS_PRP_CT_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_CT_1, 'DELIVERABLE', 'PRP-CT-110', '계약서', 'OPMS', 80, 0, 1, 1, 1, '.pdf', '계약서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_CT_1, 'DELIVERABLE', 'PRP-CT-120', '과업지시서', 'OPMS', 90, 1, 0, 0, 0, '.pdf', '과업지시서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_CT_1, 'DELIVERABLE', 'PRP-CT-130', '하도급계약서', 'OPMS', 100, 1, 0, 0, 0, '.pdf', '하도급계약서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_CT_1, 'DELIVERABLE', 'PRP-CT-140', '하도급승인신청', 'OPMS', 110, 1, 0, 0, 0, '.pdf', '하도급사전승인신청서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_CT_1, 'DELIVERABLE', 'PRP-CT-150', '기술협상안', 'OPMS', 120, 1, 0, 0, 0, '.pdf', '기술협상안');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PRP_CT, 'TASK', 'PRP-CT-2', '착수계 제출', 'OPMS', 130);
SET @t_OPMS_PRP_CT_2 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_CT_2, 'DELIVERABLE', 'PRP-CT-210', '착수계', 'OPMS', 130, 0, 1, 1, 1, '.pdf', '착수계');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_CT_2, 'DELIVERABLE', 'PRP-CT-220', '용역책임자계', 'OPMS', 140, 1, 0, 0, 0, '.pdf', '용역책임자게');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_CT_2, 'DELIVERABLE', 'PRP-CT-230', '사업수행계획서', 'OPMS', 150, 0, 1, 1, 1, '.hwpx', '사업수행계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_CT_2, 'DELIVERABLE', 'PRP-CT-240', '산출내역서', 'OPMS', 160, 0, 1, 1, 1, '.hwpx', '산출내역서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PRP_CT, 'TASK', 'PRP-CT-3', '투입인원확정', 'OPMS', 170);
SET @t_OPMS_PRP_CT_3 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_CT_3, 'DELIVERABLE', 'PRP-CT-310', '인력투입계획표', 'OPMS', 170, 0, 1, 1, 1, '.hwpx', '인력투입계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_CT_3, 'DELIVERABLE', 'PRP-CT-320', '비상연락망', 'OPMS', 180, 0, 1, 1, 1, '.hwpx', '비상연락망');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_CT_3, 'DELIVERABLE', 'PRP-CT-330', '조직도', 'OPMS', 190, 0, 1, 1, 1, '.pptx', '자리배치도');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_CT_3, 'DELIVERABLE', 'PRP-CT-340', '자리배치도', 'OPMS', 200, 1, 0, 0, 0, '.xlsx', '역할정의서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_CT_3, 'DELIVERABLE', 'PRP-CT-350', '업무분장표', 'OPMS', 210, 1, 0, 0, 0, '.hwpx', '업무분장표');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_OPMS_PRP, 'ACTIVITY', 'PRP-TL', '테일러링', 'OPMS', 220);
SET @a_OPMS_PRP_TL := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PRP_TL, 'TASK', 'PRP-TL-1', '테일러링', 'OPMS', 220);
SET @t_OPMS_PRP_TL_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_TL_1, 'DELIVERABLE', 'PRP-TL-110', '테일러링가이드', 'OPMS', 220, 1, 0, 0, 0, '.hwpx', '프로세스 테일러링 가이드');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_TL_1, 'DELIVERABLE', 'PRP-TL-120', '테일러링 결과서', 'OPMS', 230, 0, 1, 1, 1, '.xlsx', '프로세스 테일러링 결과서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_OPMS_PRP, 'ACTIVITY', 'PRP-PM', '프로젝트 관리 계획 수립', 'OPMS', 240);
SET @a_OPMS_PRP_PM := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PRP_PM, 'TASK', 'PRP-PM-1', '범위관리계획', 'OPMS', 240);
SET @t_OPMS_PRP_PM_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_PM_1, 'DELIVERABLE', 'PRP-PM-110', '범위관리계획서', 'OPMS', 240, 0, 1, 1, 1, '.hwpx', '범위관리계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PRP_PM, 'TASK', 'PRP-PM-2', '일정관리계획', 'OPMS', 250);
SET @t_OPMS_PRP_PM_2 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_PM_2, 'DELIVERABLE', 'PRP-PM-210', '일정관리계획서/WBS', 'OPMS', 250, 0, 1, 1, 1, '.hwpx', '일정및진척관리계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PRP_PM, 'TASK', 'PRP-PM-3', '위험관리계획', 'OPMS', 260);
SET @t_OPMS_PRP_PM_3 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_PM_3, 'DELIVERABLE', 'PRP-PM-310', '위험관리계획서', 'OPMS', 260, 0, 1, 1, 1, '.hwpx', '위험및이슈관리계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PRP_PM, 'TASK', 'PRP-PM-4', '품질관리계획', 'OPMS', 270);
SET @t_OPMS_PRP_PM_4 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_PM_4, 'DELIVERABLE', 'PRP-PM-410', '품질관리계획서', 'OPMS', 270, 0, 1, 1, 1, '.hwpx', '품질보증계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PRP_PM, 'TASK', 'PRP-PM-5', '인력관리계획', 'OPMS', 280);
SET @t_OPMS_PRP_PM_5 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_PM_5, 'DELIVERABLE', 'PRP-PM-510', '인력관리계획서', 'OPMS', 280, 0, 1, 1, 1, '.hwpx', '인려관리계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PRP_PM, 'TASK', 'PRP-PM-6', '형상관리계획', 'OPMS', 290);
SET @t_OPMS_PRP_PM_6 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_PM_6, 'DELIVERABLE', 'PRP-PM-610', '형상관리계획서', 'OPMS', 290, 0, 1, 1, 1, '.hwpx', '구성관리계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PRP_PM, 'TASK', 'PRP-PM-7', '변경관리계획', 'OPMS', 300);
SET @t_OPMS_PRP_PM_7 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_PM_7, 'DELIVERABLE', 'PRP-PM-710', '변경관리계획서', 'OPMS', 300, 0, 0, 0, 1, '.hwpx', '의사소통계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PRP_PM, 'TASK', 'PRP-PM-8', '의사소통계획', 'OPMS', 310);
SET @t_OPMS_PRP_PM_8 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_PM_8, 'DELIVERABLE', 'PRP-PM-810', '의사소통관리계획서', 'OPMS', 310, 0, 0, 0, 1, '.hwpx', '보안관리계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PRP_PM, 'TASK', 'PRP-PM-9', '보안관리계획', 'OPMS', 320);
SET @t_OPMS_PRP_PM_9 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_PM_9, 'DELIVERABLE', 'PRP-PM-910', '보안관리계획서', 'OPMS', 320, 0, 1, 1, 1, '.hwpx', '자원관리계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PRP_PM, 'TASK', 'PRP-PM-10', '안전보건관리', 'OPMS', 330);
SET @t_OPMS_PRP_PM_10 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PRP_PM_10, 'DELIVERABLE', 'PRP-PM-1010', '안전보건관리계획서', 'OPMS', 330, 0, 1, 1, 1, '.hwpx', '안전보건관리계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, description, methodology, sort_order) VALUES (NULL, 'PHASE', 'PPC', '실행 통제', NULL, 'OPMS', 340);
SET @ph := LAST_INSERT_ID();
SET @p_OPMS_PPC := @ph;
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_OPMS_PPC, 'ACTIVITY', 'PPC-CM', '핵심관리', 'OPMS', 340);
SET @a_OPMS_PPC_CM := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PPC_CM, 'TASK', 'PPC-CM-1', '범위관리및통제', 'OPMS', 340);
SET @t_OPMS_PPC_CM_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_CM_1, 'DELIVERABLE', 'PPC-CM-110', '범위비교표', 'OPMS', 340, 0, 1, 1, 1, '.hwpx', '범위비교표');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PPC_CM, 'TASK', 'PPC-CM-2', '일정/진척관리및통제', 'OPMS', 350);
SET @t_OPMS_PPC_CM_2 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_CM_2, 'DELIVERABLE', 'PPC-CM-210', 'WBS', 'OPMS', 350, 0, 1, 1, 1, '.xlsx', '일정관리및통제결과표');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PPC_CM, 'TASK', 'PPC-CM-3', '위험관리및통제', 'OPMS', 360);
SET @t_OPMS_PPC_CM_3 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_CM_3, 'DELIVERABLE', 'PPC-CM-310', '위험보고서', 'OPMS', 360, 1, 0, 0, 0, '.hwpx', '위험보고서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_CM_3, 'DELIVERABLE', 'PPC-CM-320', '이슈보고서', 'OPMS', 370, 1, 0, 0, 0, '.hwpx', '이슈보고서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_CM_3, 'DELIVERABLE', 'PPC-CM-330', '이슈해결보고서', 'OPMS', 380, 1, 0, 0, 0, '.hwpx', '이슈해결보고서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_CM_3, 'DELIVERABLE', 'PPC-CM-340', '위험이슈통제결과표', 'OPMS', 390, 0, 1, 1, 1, '.xlsx', '위험및이슈관리대장');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PPC_CM, 'TASK', 'PPC-CM-4', '품질관리및통제', 'OPMS', 400);
SET @t_OPMS_PPC_CM_4 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_CM_4, 'DELIVERABLE', 'PPC-CM-410', '품질목표정의서', 'OPMS', 400, 0, 0, 0, 1, '.xlsx', '품질검토관리대장');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_CM_4, 'DELIVERABLE', 'PPC-CM-420', '품질검토결과보고서', 'OPMS', 410, 1, 0, 0, 0, '.hwpx', '품질검토결과서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PPC_CM, 'TASK', 'PPC-CM-5', '투입인력보고', 'OPMS', 420);
SET @t_OPMS_PPC_CM_5 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_CM_5, 'DELIVERABLE', 'PPC-CM-510', '투입인력보고서', 'OPMS', 420, 0, 0, 0, 1, '.xlsx', '인력투입보고서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PPC_CM, 'TASK', 'PPC-CM-6', '형상관리및통제', 'OPMS', 430);
SET @t_OPMS_PPC_CM_6 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_CM_6, 'DELIVERABLE', 'PPC-CM-610', '베이스라인관리대장', 'OPMS', 430, 0, 0, 1, 1, '.hwpx', '베이스라인감사보고서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_CM_6, 'DELIVERABLE', 'PPC-CM-620', '형상변경관리대장', 'OPMS', 440, 0, 0, 1, 1, '.hwpx', '구성항목관리대장');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PPC_CM, 'TASK', 'PPC-CM-7', '변경관리및통제', 'OPMS', 450);
SET @t_OPMS_PPC_CM_7 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_CM_7, 'DELIVERABLE', 'PPC-CM-710', '변경요청목록대장', 'OPMS', 450, 0, 0, 0, 1, '.xlsx', '변경요청관리대장');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_CM_7, 'DELIVERABLE', 'PPC-CM-720', '변경요청서', 'OPMS', 460, 1, 0, 0, 0, '.hwpx', '변경요청서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_OPMS_PPC, 'ACTIVITY', 'PPC-SM', '단순관리', 'OPMS', 470);
SET @a_OPMS_PPC_SM := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PPC_SM, 'TASK', 'PPC-SM-1', '의사관리및통제', 'OPMS', 470);
SET @t_OPMS_PPC_SM_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_SM_1, 'DELIVERABLE', 'PPC-SM-110', '회의록', 'OPMS', 470, 0, 1, 1, 1, '.hwpx', '회의록');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_SM_1, 'DELIVERABLE', 'PPC-SM-120', '주간업무보고', 'OPMS', 480, 0, 1, 1, 1, '.hwpx', '주간업무보고서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_SM_1, 'DELIVERABLE', 'PPC-SM-130', '월간업무보고', 'OPMS', 490, 0, 1, 1, 1, '.hwpx', '월간업무보고서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_SM_1, 'DELIVERABLE', 'PPC-SM-140', '수시보고서', 'OPMS', 500, 0, 1, 1, 1, '.hwpx', '수시보고서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_SM_1, 'DELIVERABLE', 'PPC-SM-150', '공문관리대장', 'OPMS', 510, 1, 0, 0, 0, '.hwpx', '공문관리대장');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PPC_SM, 'TASK', 'PPC-SM-2', '보안관리/통제', 'OPMS', 520);
SET @t_OPMS_PPC_SM_2 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_SM_2, 'DELIVERABLE', 'PPC-SM-210', '보안관리대장', 'OPMS', 520, 1, 0, 0, 0, '.hwpx', '보안관리대장');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PPC_SM, 'TASK', 'PPC-SM-3', '안전관리/통제', 'OPMS', 530);
SET @t_OPMS_PPC_SM_3 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_SM_3, 'DELIVERABLE', 'PPC-SM-310', '안전보건수행결과서', 'OPMS', 530, 0, 1, 1, 1, '.hwpx', '안전보건수행결과서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PPC_SM, 'TASK', 'PPC-SM-4', '감리', 'OPMS', 540);
SET @t_OPMS_PPC_SM_4 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_SM_4, 'DELIVERABLE', 'PPC-SM-410', '감리시정조치계획서', 'OPMS', 540, 1, 0, 0, 0, '.hwpx', '감리시정조치계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PPC_SM_4, 'DELIVERABLE', 'PPC-SM-420', '감리시정조치결과서', 'OPMS', 550, 1, 0, 0, 0, '.hwpx', '감리시정조치결과서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, description, methodology, sort_order) VALUES (NULL, 'PHASE', 'PED', '종료 (Project End)', NULL, 'OPMS', 560);
SET @ph := LAST_INSERT_ID();
SET @p_OPMS_PED := @ph;
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_OPMS_PED, 'ACTIVITY', 'PED-EE', '외부종료', 'OPMS', 560);
SET @a_OPMS_PED_EE := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PED_EE, 'TASK', 'PED-EE-1', '검수', 'OPMS', 560);
SET @t_OPMS_PED_EE_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PED_EE_1, 'DELIVERABLE', 'PED-EE-110', '검수계획서', 'OPMS', 560, 1, 0, 0, 0, '.hwpx', '검수계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PED_EE_1, 'DELIVERABLE', 'PED-EE-120', '검수요청서(공문)', 'OPMS', 570, 0, 1, 1, 1, '.pdf', '검수요청서(공문)');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PED_EE_1, 'DELIVERABLE', 'PED-EE-130', '준공검사확인서', 'OPMS', 580, 0, 1, 1, 1, '.pdf', '준공검사확인서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PED_EE_1, 'DELIVERABLE', 'PED-EE-140', '검사확인서', 'OPMS', 590, 0, 1, 1, 1, '.hwpx', '검사확인서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PED_EE_1, 'DELIVERABLE', 'PED-EE-150', '준공조서', 'OPMS', 600, 0, 1, 1, 1, '.hwpx', '준공조서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PED_EE_1, 'DELIVERABLE', 'PED-EE-160', '인수인계계획서', 'OPMS', 610, 0, 1, 1, 1, '.xlsx', '인수인계계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PED_EE_1, 'DELIVERABLE', 'PED-EE-170', '기능점수산출내역', 'OPMS', 620, 0, 0, 1, 1, '.hwpx', '기능점수산출내역');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OPMS_PED_EE, 'TASK', 'PED-EE-2', '사업완료', 'OPMS', 630);
SET @t_OPMS_PED_EE_2 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PED_EE_2, 'DELIVERABLE', 'PED-EE-210', '프로젝트 완료보고서', 'OPMS', 630, 0, 1, 1, 1, '.hwpx', '프로젝트 완료보고서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PED_EE_2, 'DELIVERABLE', 'PED-EE-220', '최종산출물', 'OPMS', 640, 0, 1, 1, 1, NULL, '최종산출물');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OPMS_PED_EE_2, 'DELIVERABLE', 'PED-EE-230', '무상 하자보수계획서', 'OPMS', 650, 0, 1, 1, 1, '.hwpx', '무상 하자보수계획서');
-- OPMS: PHASE 4 · ACTIVITY 8 · TASK 31 · DELIVERABLE 65

-- ===== ODS (02. ODS(시스템 구축)) =====
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, description, methodology, sort_order) VALUES (NULL, 'PHASE', 'RAD', '분석 (Require Analysis Define)', NULL, 'ODS', 10);
SET @ph := LAST_INSERT_ID();
SET @p_ODS_RAD := @ph;
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_ODS_RAD, 'ACTIVITY', 'RAD-RC', '요구사항 분석 (Requirement Collection)', 'ODS', 10);
SET @a_ODS_RAD_RC := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_ODS_RAD_RC, 'TASK', 'RAD-RC-1', '요구사항정의', 'ODS', 10);
SET @t_ODS_RAD_RC_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_RAD_RC_1, 'DELIVERABLE', 'RAD-RC-110', '현행시스템 분석서', 'ODS', 10, 0, 0, 1, 1, '.hwpx', '현행시스템 분석서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_RAD_RC_1, 'DELIVERABLE', 'RAD-RC-120', '면담계획서', 'ODS', 20, 1, 0, 0, 0, '.hwpx', '면담계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_RAD_RC_1, 'DELIVERABLE', 'RAD-RC-130', '면담결과서', 'ODS', 30, 1, 0, 0, 0, '.hwpx', '면담결과서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_ODS_RAD, 'ACTIVITY', 'RAD-RD', '요구사항 정의 (Requirement Definition)', 'ODS', 40);
SET @a_ODS_RAD_RD := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_ODS_RAD_RD, 'TASK', 'RAD-RD-1', '요구사항 분석', 'ODS', 40);
SET @t_ODS_RAD_RD_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_RAD_RD_1, 'DELIVERABLE', 'RAD-RD-110', '요구사항정의서', 'ODS', 40, 0, 0, 1, 1, '.xlsx', '요구사항정의서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_RAD_RD_1, 'DELIVERABLE', 'RAD-RD-120', '요구사항추적표', 'ODS', 50, 0, 0, 1, 1, '.xlsx', '요구사항추적표');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, description, methodology, sort_order) VALUES (NULL, 'PHASE', 'AAD', '설계 (Application Analysis Design)', NULL, 'ODS', 60);
SET @ph := LAST_INSERT_ID();
SET @p_ODS_AAD := @ph;
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_ODS_AAD, 'ACTIVITY', 'AAD-DD', 'DB 설계 (Database Design)', 'ODS', 60);
SET @a_ODS_AAD_DD := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_ODS_AAD_DD, 'TASK', 'AAD-DD-1', 'DB설계', 'ODS', 60);
SET @t_ODS_AAD_DD_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_DD_1, 'DELIVERABLE', 'AAD-DD-110', '표준 단어 사전', 'ODS', 60, 0, 0, 0, 1, '.xlsx', '표준 단어 사전');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_DD_1, 'DELIVERABLE', 'AAD-DD-120', '표준 도메인 사전', 'ODS', 70, 0, 0, 0, 1, '.xlsx', '표준 도메인 사전');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_DD_1, 'DELIVERABLE', 'AAD-DD-130', '표준 용어 사전', 'ODS', 80, 0, 0, 1, 1, '.xlsx', '표준 용어 사전');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_DD_1, 'DELIVERABLE', 'AAD-DD-140', '표준 코드 정의서', 'ODS', 90, 1, 0, 0, 0, '.xlsx', '표준 코드 정의서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_ODS_AAD_DD, 'TASK', 'AAD-DD-2', '논리 데이터 설계', 'ODS', 100);
SET @t_ODS_AAD_DD_2 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_DD_2, 'DELIVERABLE', 'AAD-DD-210', '논리 ERD', 'ODS', 100, 0, 0, 0, 1, '.xlsx', '논리 ERD');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_DD_2, 'DELIVERABLE', 'AAD-DD-220', '엔터티(Entity) 정의서', 'ODS', 110, 0, 0, 0, 1, '.xlsx', '엔터티(Entity) 정의서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_DD_2, 'DELIVERABLE', 'AAD-DD-230', '속성(Attribute) 정의서', 'ODS', 120, 1, 0, 0, 0, '.xlsx', '속성(Attribute) 정의서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_ODS_AAD_DD, 'TASK', 'AAD-DD-3', '물리데이터 설계', 'ODS', 130);
SET @t_ODS_AAD_DD_3 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_DD_3, 'DELIVERABLE', 'AAD-DD-310', '물리 ERD', 'ODS', 130, 0, 0, 1, 1, '.xlsx', '물리 ERD');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_DD_3, 'DELIVERABLE', 'AAD-DD-320', '데이터베이스 정의서', 'ODS', 140, 0, 1, 1, 1, '.xlsx', '데이터베이스 정의서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_DD_3, 'DELIVERABLE', 'AAD-DD-330', '테이블(Table) 정의서', 'ODS', 150, 0, 1, 1, 1, '.xlsx', '테이블(Table) 정의서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_DD_3, 'DELIVERABLE', 'AAD-DD-340', '컬럼(Column) 정의서', 'ODS', 160, 0, 1, 1, 1, '.xlsx', '컬럼(Column) 정의서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_DD_3, 'DELIVERABLE', 'AAD-DD-350', '오브젝트 정의서', 'ODS', 170, 0, 1, 1, 1, '.xlsx', '오브젝트 정의서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_ODS_AAD, 'ACTIVITY', 'AAD-FD', '기능설계 (Functional Design)', 'ODS', 180);
SET @a_ODS_AAD_FD := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_ODS_AAD_FD, 'TASK', 'AAD-FD-1', '아키텍쳐 설계', 'ODS', 180);
SET @t_ODS_AAD_FD_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_FD_1, 'DELIVERABLE', 'AAD-FD-110', '아키텍처 설계서', 'ODS', 180, 0, 1, 1, 1, '.hwpx', '아키텍처 설계서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_FD_1, 'DELIVERABLE', 'AAD-FD-120', '연계 인터페이스 설계서', 'ODS', 190, 0, 1, 1, 1, '.hwpx', '연계 인터페이스 설계서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_FD_1, 'DELIVERABLE', 'AAD-FD-130', '보안설계서', 'ODS', 200, 1, 0, 0, 0, '.hwpx', '보안설계서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_FD_1, 'DELIVERABLE', 'AAD-FD-140', '개발표준정의서', 'ODS', 210, 0, 1, 1, 1, '.hwpx', '개발표준정의서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_ODS_AAD_FD, 'TASK', 'AAD-FD-2', 'UI 설계', 'ODS', 220);
SET @t_ODS_AAD_FD_2 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_FD_2, 'DELIVERABLE', 'AAD-FD-210', '사용자그룹정의서', 'ODS', 220, 0, 1, 1, 1, '.xlsx', '사용자그룹정의서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_FD_2, 'DELIVERABLE', 'AAD-FD-220', '메뉴 구조도', 'ODS', 230, 0, 1, 1, 1, '.xlsx', '메뉴 구조도');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_FD_2, 'DELIVERABLE', 'AAD-FD-230', '화면 설계서', 'ODS', 240, 0, 1, 1, 1, '.hwpx', '화면 설계서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_FD_2, 'DELIVERABLE', 'AAD-FD-240', '웹접근성 및 웹표준 점검표', 'ODS', 250, 0, 1, 1, 1, '.xlsx', '웹접근성 및 웹표준 점검표');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_ODS_AAD_FD, 'TASK', 'AAD-FD-3', '애플리케이션 설계', 'ODS', 260);
SET @t_ODS_AAD_FD_3 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_FD_3, 'DELIVERABLE', 'AAD-FD-310', '프로그램 목록', 'ODS', 260, 0, 1, 1, 1, '.xlsx', '프로그램 목록');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_FD_3, 'DELIVERABLE', 'AAD-FD-320', '클래스 모형기술서', 'ODS', 270, 0, 1, 1, 1, '.xlsx', '클래스 모형기술서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_FD_3, 'DELIVERABLE', 'AAD-FD-330', '시퀀스 모형기술서', 'ODS', 280, 0, 1, 1, 1, '.xlsx', '시퀀스 모형기술서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_ODS_AAD, 'ACTIVITY', 'AAD-TP', '테스트 및 전환계획 (Test & Transition Planning)', 'ODS', 290);
SET @a_ODS_AAD_TP := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_ODS_AAD_TP, 'TASK', 'AAD-TP-1', '테스트 계획 수립', 'ODS', 290);
SET @t_ODS_AAD_TP_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_TP_1, 'DELIVERABLE', 'AAD-TP-110', '단위테스트 계획서', 'ODS', 290, 0, 1, 1, 1, '.hwpx', '단위테스트 계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_TP_1, 'DELIVERABLE', 'AAD-TP-120', '단위테스트 시나리오', 'ODS', 300, 0, 1, 1, 1, '.xlsx', '붙임1. 단위테스트 시나리오');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_TP_1, 'DELIVERABLE', 'AAD-TP-130', '통합테스트 계획서', 'ODS', 310, 0, 1, 1, 1, '.hwpx', '통합테스트 계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_TP_1, 'DELIVERABLE', 'AAD-TP-140', '통합테스트 시나리오', 'ODS', 320, 0, 1, 1, 1, '.xlsx', '붙임1. 통합테스트 시나리오');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_TP_1, 'DELIVERABLE', 'AAD-TP-150', '인수테스트 계획서', 'ODS', 330, 0, 1, 1, 1, '.hwpx', '인수테스트 계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_TP_1, 'DELIVERABLE', 'AAD-TP-160', '인수테스트 시나리오', 'ODS', 340, 0, 1, 1, 1, '.xlsx', '붙임1. 인수테스트 시나리오');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_TP_1, 'DELIVERABLE', 'AAD-TP-170', '성능테스트계획서', 'ODS', 350, 0, 1, 1, 1, '.hwpx', '성능테스트계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_TP_1, 'DELIVERABLE', 'AAD-TP-180', '보안취약점 점검계획서', 'ODS', 360, 0, 1, 1, 1, '.hwpx', '보안취약점 점검계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_ODS_AAD_TP, 'TASK', 'AAD-TP-2', '전환 계획 수립', 'ODS', 370);
SET @t_ODS_AAD_TP_2 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_TP_2, 'DELIVERABLE', 'AAD-TP-210', '구축계획서', 'ODS', 370, 0, 1, 1, 1, '.hwpx', '구축계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_TP_2, 'DELIVERABLE', 'AAD-TP-220', '시스템 전환 계획서', 'ODS', 380, 0, 1, 1, 1, '.hwpx', '시스템 전환 계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_AAD_TP_2, 'DELIVERABLE', 'AAD-TP-230', '데이터 전환 계획서', 'ODS', 390, 0, 0, 1, 1, '.hwpx', '데이터 전환 계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, description, methodology, sort_order) VALUES (NULL, 'PHASE', 'DTD', '구현/인수', NULL, 'ODS', 400);
SET @ph := LAST_INSERT_ID();
SET @p_ODS_DTD := @ph;
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_ODS_DTD, 'ACTIVITY', 'DTD-IM', '구현 (Implementation)', 'ODS', 400);
SET @a_ODS_DTD_IM := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_ODS_DTD_IM, 'TASK', 'DTD-IM-1', '소프트웨어 개발', 'ODS', 400);
SET @t_ODS_DTD_IM_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_DTD_IM_1, 'DELIVERABLE', 'DTD-IM-110', '프로그램소스', 'ODS', 400, 0, 1, 1, 1, '.hwpx', '프로그램소스');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_DTD_IM_1, 'DELIVERABLE', 'DTD-IM-120', '코드 인스펙션 결과서', 'ODS', 410, 0, 1, 1, 1, '.hwpx', '코드 인스펙션 결과서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_DTD_IM_1, 'DELIVERABLE', 'DTD-IM-130', '단위테스트 결과서', 'ODS', 420, 0, 1, 1, 1, '.xlsx', '단위테스트 결과서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_DTD_IM_1, 'DELIVERABLE', 'DTD-IM-140', '웹접근성 및 웹표준 점검 결과서', 'ODS', 430, 1, 0, 0, 0, '.hwpx', '웹접근성 및 웹표준 점검 결과서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_ODS_DTD_IM, 'TASK', 'DTD-IM-2', '인프라 구축', 'ODS', 440);
SET @t_ODS_DTD_IM_2 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_DTD_IM_2, 'DELIVERABLE', 'DTD-IM-210', '구축 결과서', 'ODS', 440, 0, 1, 1, 1, '.xlsx', '구축 결과서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_ODS_DTD_IM, 'TASK', 'DTD-IM-3', '지침서 작성', 'ODS', 450);
SET @t_ODS_DTD_IM_3 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_DTD_IM_3, 'DELIVERABLE', 'DTD-IM-310', '사용자 지침서', 'ODS', 450, 0, 1, 1, 1, '.hwpx', '사용자 지침서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_DTD_IM_3, 'DELIVERABLE', 'DTD-IM-320', '운영자 지침서', 'ODS', 460, 0, 1, 1, 1, '.xlsx', '운영자 지침서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_ODS_DTD, 'ACTIVITY', 'DTD-TS', '테스트 (Testing)', 'ODS', 470);
SET @a_ODS_DTD_TS := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_ODS_DTD_TS, 'TASK', 'DTD-TS-1', '테스트', 'ODS', 470);
SET @t_ODS_DTD_TS_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_DTD_TS_1, 'DELIVERABLE', 'DTD-TS-110', '통합테스트 결과서', 'ODS', 470, 0, 0, 1, 1, '.hwpx', '통합테스트 결과서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_DTD_TS_1, 'DELIVERABLE', 'DTD-TS-120', '성능테스트 결과서', 'ODS', 480, 0, 0, 1, 1, '.hwpx', '성능테스트 결과서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_DTD_TS_1, 'DELIVERABLE', 'DTD-TS-130', '보안취약점 점검 결과서', 'ODS', 490, 0, 1, 1, 1, '.hwpx', '보안취약점 점검 결과서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_ODS_DTD, 'ACTIVITY', 'DTD-DP', '전개 (Deployment)', 'ODS', 500);
SET @a_ODS_DTD_DP := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_ODS_DTD_DP, 'TASK', 'DTD-DP-1', '시스템 전환', 'ODS', 500);
SET @t_ODS_DTD_DP_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_DTD_DP_1, 'DELIVERABLE', 'DTD-DP-110', '시스템 전환 보고서', 'ODS', 500, 0, 1, 1, 1, '.hwpx', '시스템 전환 보고서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_DTD_DP_1, 'DELIVERABLE', 'DTD-DP-120', '데이터 전환 보고서', 'ODS', 510, 0, 0, 1, 1, '.hwpx', '데이터 전환 보고서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_ODS_DTD_DP, 'TASK', 'DTD-DP-2', '인수테스트', 'ODS', 520);
SET @t_ODS_DTD_DP_2 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_DTD_DP_2, 'DELIVERABLE', 'DTD-DP-210', '인수테스트 결과서', 'ODS', 520, 0, 0, 1, 1, '.hwpx', '인수테스트 결과서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_ODS_DTD_DP, 'TASK', 'DTD-DP-3', '사용자교육', 'ODS', 530);
SET @t_ODS_DTD_DP_3 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_DTD_DP_3, 'DELIVERABLE', 'DTD-DP-310', '교육계획서', 'ODS', 530, 0, 1, 1, 1, '.hwpx', '교육계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_DTD_DP_3, 'DELIVERABLE', 'DTD-DP-320', '교육결과서', 'ODS', 540, 0, 1, 1, 1, '.hwpx', '교육결과서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_ODS_DTD, 'ACTIVITY', 'DTD-PS', '오픈 안정화 (Post Stabilization)', 'ODS', 550);
SET @a_ODS_DTD_PS := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_ODS_DTD_PS, 'TASK', 'DTD-PS-1', '오픈 안정화', 'ODS', 550);
SET @t_ODS_DTD_PS_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_DTD_PS_1, 'DELIVERABLE', 'DTD-PS-110', '안정화 지원 계획서', 'ODS', 550, 0, 0, 1, 1, '.hwpx', '안정화 지원 계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_DTD_PS_1, 'DELIVERABLE', 'DTD-PS-120', '안정화 지원 결과서', 'ODS', 560, 0, 0, 1, 1, '.hwpx', '안정화 지원 결과서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_DTD_PS_1, 'DELIVERABLE', 'DTD-PS-130', '초기 이슈 및 결함 조치대장', 'ODS', 570, 0, 0, 1, 1, '.xlsx', '초기 이슈 및 결함 조치대장');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_ODS_DTD_PS_1, 'DELIVERABLE', 'DTD-PS-140', '인수인계 계획서', 'ODS', 580, 0, 0, 1, 1, '.hwpx', '인수인계 계획서');
-- ODS: PHASE 3 · ACTIVITY 9 · TASK 18 · DELIVERABLE 58

-- ===== OMS (03. OMS(유지보수)) =====
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, description, methodology, sort_order) VALUES (NULL, 'PHASE', 'SLM', '서비스 수준 관리 (Service Level Management)', '운영 (System Operation Services)(SOS) 하위', 'OMS', 10);
SET @ph := LAST_INSERT_ID();
SET @p_OMS_SLM := @ph;
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_OMS_SLM, 'ACTIVITY', 'SLM-SL', '서비스 수준 (Service Level )', 'OMS', 10);
SET @a_OMS_SLM_SL := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OMS_SLM_SL, 'TASK', 'SLM-SL-1', '표준 정의', 'OMS', 10);
SET @t_OMS_SLM_SL_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_SLM_SL_1, 'DELIVERABLE', 'SLM-SL-110', 'SOP', 'OMS', 10, 0, 1, 1, 1, '.hwpx', 'SOP');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_SLM_SL_1, 'DELIVERABLE', 'SLM-SL-120', 'SPM 개선 계획서', 'OMS', 20, 0, 0, 0, 1, '.hwpx', 'SPM 개선 계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_SLM_SL_1, 'DELIVERABLE', 'SLM-SL-130', 'SPM 개선 결과서', 'OMS', 30, 0, 0, 0, 1, '.hwpx', 'SPM 개선 결과서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OMS_SLM_SL, 'TASK', 'SLM-SL-2', '수준관리', 'OMS', 40);
SET @t_OMS_SLM_SL_2 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_SLM_SL_2, 'DELIVERABLE', 'SLM-SL-210', 'SLA', 'OMS', 40, 0, 1, 1, 1, '.hwpx', 'SLA');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, description, methodology, sort_order) VALUES (NULL, 'PHASE', 'AMS', '가용성 관리 (Availability Management System)', '운영 (System Operation Services)(SOS) 하위', 'OMS', 50);
SET @ph := LAST_INSERT_ID();
SET @p_OMS_AMS := @ph;
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_OMS_AMS, 'ACTIVITY', 'AMS-HM', '서비스 점검', 'OMS', 50);
SET @a_OMS_AMS_HM := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OMS_AMS_HM, 'TASK', 'AMS-HM-1', '계획 수립', 'OMS', 50);
SET @t_OMS_AMS_HM_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_AMS_HM_1, 'DELIVERABLE', 'AMS-HM-110', '일일점검계획서', 'OMS', 50, 1, 0, 0, 0, '.hwpx', '일일점검계획서_점검시스템명_00.00.00');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_AMS_HM_1, 'DELIVERABLE', 'AMS-HM-120', '월간점검계획서', 'OMS', 60, 0, 0, 1, 1, '.hwpx', '월간점검계획서_점검시스템명_00.00월');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_AMS_HM_1, 'DELIVERABLE', 'AMS-HM-130', '분기점검계획서', 'OMS', 70, 0, 0, 1, 1, '.hwpx', '분기점검계획서_점검시스템명_0분기');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_AMS_HM_1, 'DELIVERABLE', 'AMS-HM-140', '반기점검계획서', 'OMS', 80, 0, 0, 0, 1, '.hwpx', '반기점검계획서_점검시스템명_0반기');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_AMS_HM_1, 'DELIVERABLE', 'AMS-HM-150', '보안점검계획서', 'OMS', 90, 0, 1, 1, 1, '.hwpx', '보안점검계획서_점검시스템명');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_AMS_HM_1, 'DELIVERABLE', 'AMS-HM-160', '수시점검계획서', 'OMS', 100, 1, 0, 0, 0, '.hwpx', '수시점검계획서_점검시스템명');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_AMS_HM_1, 'DELIVERABLE', 'AMS-HM-170', '특별점검계획서', 'OMS', 110, 1, 0, 0, 0, '.hwpx', '특별점검계획서_점검시스템명');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OMS_AMS_HM, 'TASK', 'AMS-HM-2', '결과보고', 'OMS', 120);
SET @t_OMS_AMS_HM_2 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_AMS_HM_2, 'DELIVERABLE', 'AMS-HM-210', '일일점검결과서', 'OMS', 120, 1, 0, 0, 0, '.hwpx', '일일점검결과서_점검시스템명_00.00.00.');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_AMS_HM_2, 'DELIVERABLE', 'AMS-HM-220', '월간점검결과서', 'OMS', 130, 0, 0, 1, 1, '.hwpx', '일일점검결과서_00.00월');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_AMS_HM_2, 'DELIVERABLE', 'AMS-HM-230', '분기점검결과서', 'OMS', 140, 0, 0, 1, 1, '.hwpx', '분기점검결과서_점검시스템명_0분기');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_AMS_HM_2, 'DELIVERABLE', 'AMS-HM-240', '반기점검결과서', 'OMS', 150, 0, 0, 0, 1, '.hwpx', '반기점검결과서_점검시스템명_0반기');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_AMS_HM_2, 'DELIVERABLE', 'AMS-HM-250', '보안점검결과서', 'OMS', 160, 0, 1, 1, 1, '.hwpx', '보안점검결과서_점검시스템명');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_AMS_HM_2, 'DELIVERABLE', 'AMS-HM-260', '수시점검결과서', 'OMS', 170, 1, 0, 0, 0, '.hwpx', '수시점검결과서_점검시스템명');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_AMS_HM_2, 'DELIVERABLE', 'AMS-HM-270', '특별점검결과서', 'OMS', 180, 1, 0, 0, 0, '.hwpx', '특별점검결과서_점검시스템명');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, description, methodology, sort_order) VALUES (NULL, 'PHASE', 'BCM', '연속성 관리 (usiness Continuity Management)', '운영 (System Operation Services)(SOS) 하위', 'OMS', 190);
SET @ph := LAST_INSERT_ID();
SET @p_OMS_BCM := @ph;
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_OMS_BCM, 'ACTIVITY', 'BCM-EM', '교육관리', 'OMS', 190);
SET @a_OMS_BCM_EM := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OMS_BCM_EM, 'TASK', 'BCM-EM-1', '교육관리', 'OMS', 190);
SET @t_OMS_BCM_EM_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_BCM_EM_1, 'DELIVERABLE', 'BCM-EM-110', '교육계획서', 'OMS', 190, 0, 1, 1, 1, '.hwpx', '교육계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_BCM_EM_1, 'DELIVERABLE', 'BCM-EM-120', '교육결과서', 'OMS', 200, 0, 1, 1, 1, '.hwpx', '교육결과서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_OMS_BCM, 'ACTIVITY', 'BCM-DM', '재난관리', 'OMS', 210);
SET @a_OMS_BCM_DM := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OMS_BCM_DM, 'TASK', 'BCM-DM-2', '재해복구', 'OMS', 210);
SET @t_OMS_BCM_DM_2 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_BCM_DM_2, 'DELIVERABLE', 'BCM-DM-210', '재해복구관리 계획서', 'OMS', 210, 0, 0, 1, 1, '.hwpx', '재해복구관리 계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_BCM_DM_2, 'DELIVERABLE', 'BCM-DM-220', '재해복구관리 매뉴얼', 'OMS', 220, 0, 0, 1, 1, '.hwpx', '재해복구관리 매뉴얼');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_BCM_DM_2, 'DELIVERABLE', 'BCM-DM-230', '재해복구 관리 교육계획서', 'OMS', 230, 0, 0, 0, 1, '.hwpx', '재해복구 관리 교육계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_BCM_DM_2, 'DELIVERABLE', 'BCM-DM-240', '재해복구 관리 교육 교재', 'OMS', 240, 0, 0, 0, 1, '.hwpx', '재해복구 관리 교육 교재');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_BCM_DM_2, 'DELIVERABLE', 'BCM-DM-250', '재해복구 관리 교육결과서', 'OMS', 250, 0, 0, 0, 1, '.hwpx', '재해복구 관리 교육결과서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_BCM_DM_2, 'DELIVERABLE', 'BCM-DM-260', '재해복구 모의훈련 계획서', 'OMS', 260, 0, 0, 0, 1, '.hwpx', '재해복구 모의훈련 계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_BCM_DM_2, 'DELIVERABLE', 'BCM-DM-270', '재해복구 모의훈련 결과서', 'OMS', 270, 0, 0, 0, 1, '.hwpx', '재해복구 모의훈련 결과서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, description, methodology, sort_order) VALUES (NULL, 'PHASE', 'IMS', '장애관리 (Incident Management System)', '지원 (User Support Services)(USS) 하위', 'OMS', 280);
SET @ph := LAST_INSERT_ID();
SET @p_OMS_IMS := @ph;
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_OMS_IMS, 'ACTIVITY', 'IMS-IM', '장애관리', 'OMS', 280);
SET @a_OMS_IMS_IM := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OMS_IMS_IM, 'TASK', 'IMS-IM-1', '장애관리', 'OMS', 280);
SET @t_OMS_IMS_IM_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_IMS_IM_1, 'DELIVERABLE', 'IMS-IM-110', '장애보고서', 'OMS', 280, 0, 1, 1, 1, '.hwpx', '장애보고서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_IMS_IM_1, 'DELIVERABLE', 'IMS-IM-120', '장애관리대장', 'OMS', 290, 0, 1, 1, 1, '.xlsx', '장애관리대장');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, description, methodology, sort_order) VALUES (NULL, 'PHASE', 'SRM', '서비스요청관리 (Service Request Management)', '지원 (User Support Services)(USS) 하위', 'OMS', 300);
SET @ph := LAST_INSERT_ID();
SET @p_OMS_SRM := @ph;
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_OMS_SRM, 'ACTIVITY', 'SRM-SM', '서비스요청관리', 'OMS', 300);
SET @a_OMS_SRM_SM := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OMS_SRM_SM, 'TASK', 'SRM-SM-1', '서비스요청관리', 'OMS', 300);
SET @t_OMS_SRM_SM_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_SRM_SM_1, 'DELIVERABLE', 'SRM-SM-110', '서비스요청관리대장', 'OMS', 300, 0, 1, 1, 1, '.xlsx', '서비스요청관리대장');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, description, methodology, sort_order) VALUES (NULL, 'PHASE', 'CCP', '변경관리 (Change Control Process)', '지원 (User Support Services)(USS) 하위', 'OMS', 310);
SET @ph := LAST_INSERT_ID();
SET @p_OMS_CCP := @ph;
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_OMS_CCP, 'ACTIVITY', 'CCP-CM', '변경관리', 'OMS', 310);
SET @a_OMS_CCP_CM := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OMS_CCP_CM, 'TASK', 'CCP-CM-1', '변경관리', 'OMS', 310);
SET @t_OMS_CCP_CM_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_CCP_CM_1, 'DELIVERABLE', 'CCP-CM-110', '변경요청서', 'OMS', 310, 0, 1, 1, 1, '.hwpx', '변경요청서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_CCP_CM_1, 'DELIVERABLE', 'CCP-CM-120', '회의록', 'OMS', 320, 0, 1, 1, 1, '.hwpx', '회의록');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_CCP_CM_1, 'DELIVERABLE', 'CCP-CM-130', '변경계획서', 'OMS', 330, 0, 1, 1, 1, '.hwpx', '변경계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_CCP_CM_1, 'DELIVERABLE', 'CCP-CM-140', '소스코드', 'OMS', 340, 0, 1, 1, 1, NULL, '소스코드');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_CCP_CM_1, 'DELIVERABLE', 'CCP-CM-150', '형상관리 대상 제출산출물', 'OMS', 350, 0, 0, 0, 1, '.xlsx', '형상관리 대상 제출산출물');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_CCP_CM_1, 'DELIVERABLE', 'CCP-CM-160', '통합테스트 결과', 'OMS', 360, 0, 1, 1, 1, '.xlsx', '통합테스트 결과');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_OMS_CCP, 'ACTIVITY', 'CCP-RM', '배포관리', 'OMS', 370);
SET @a_OMS_CCP_RM := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_OMS_CCP_RM, 'TASK', 'CCP-RM-1', '배포관리', 'OMS', 370);
SET @t_OMS_CCP_RM_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_CCP_RM_1, 'DELIVERABLE', 'CCP-RM-110', '배포계획서', 'OMS', 370, 0, 1, 1, 1, '.hwpx', '배포계획서');
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order, is_optional, required_small, required_medium, required_large, doc_format, file_name_base) VALUES (@t_OMS_CCP_RM_1, 'DELIVERABLE', 'CCP-RM-120', '배포결과서', 'OMS', 380, 0, 1, 1, 1, '.hwpx', '배포결과서');
-- OMS: PHASE 6 · ACTIVITY 8 · TASK 10 · DELIVERABLE 38

-- ===== BIS (06.BIS(ISP컨설팅)) =====
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, description, methodology, sort_order) VALUES (NULL, 'PHASE', 'AFA', '확인/분석 (AS-IS Finding/Analysis)', NULL, 'BIS', 10);
SET @ph := LAST_INSERT_ID();
SET @p_BIS_AFA := @ph;
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_BIS_AFA, 'ACTIVITY', 'AFA-ID', '정보화 방향성 확인 (Information Direction)', 'BIS', 10);
SET @a_BIS_AFA_ID := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_BIS_AFA_ID, 'TASK', 'AFA-ID-1', '정보환경분석', 'BIS', 10);
SET @t_BIS_AFA_ID_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_BIS_AFA_ID, 'TASK', 'AFA-ID-2', '정보기술동향분석', 'BIS', 20);
SET @t_BIS_AFA_ID_2 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_BIS_AFA_ID, 'TASK', 'AFA-ID-3', 'ISP방향성 수립', 'BIS', 30);
SET @t_BIS_AFA_ID_3 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_BIS_AFA, 'ACTIVITY', 'AFA-AA', '현황분석 (AS-IS Analysis)', 'BIS', 40);
SET @a_BIS_AFA_AA := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_BIS_AFA_AA, 'TASK', 'AFA-AA-1', '정보관리아키텍처분석', 'BIS', 40);
SET @t_BIS_AFA_AA_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_BIS_AFA_AA, 'TASK', 'AFA-AA-2', '인프라아키텍처분석', 'BIS', 50);
SET @t_BIS_AFA_AA_2 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_BIS_AFA_AA, 'TASK', 'AFA-AA-3', '정보아키텍처분석', 'BIS', 60);
SET @t_BIS_AFA_AA_3 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_BIS_AFA_AA, 'TASK', 'AFA-AA-4', '정보개선기회도출', 'BIS', 70);
SET @t_BIS_AFA_AA_4 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, description, methodology, sort_order) VALUES (NULL, 'PHASE', 'IMD', '모델설계(Improve Model Design)', NULL, 'BIS', 80);
SET @ph := LAST_INSERT_ID();
SET @p_BIS_IMD := @ph;
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_BIS_IMD, 'ACTIVITY', 'IMD-CD', '개선모델 개념설계 (Concept Design)', 'BIS', 80);
SET @a_BIS_IMD_CD := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_BIS_IMD_CD, 'TASK', 'IMD-CD-1', '서식/코드표준화방안 수립', 'BIS', 80);
SET @t_BIS_IMD_CD_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_BIS_IMD_CD, 'TASK', 'IMD-CD-2', '시스템연계방안 수립', 'BIS', 90);
SET @t_BIS_IMD_CD_2 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_BIS_IMD_CD, 'TASK', 'IMD-CD-3', '현업검증', 'BIS', 100);
SET @t_BIS_IMD_CD_3 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_BIS_IMD_CD, 'TASK', 'IMD-CD-4', '개선과제정의', 'BIS', 110);
SET @t_BIS_IMD_CD_4 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_BIS_IMD, 'ACTIVITY', 'IMD-DD', '개선모델 상세설계 (Detail Design)', 'BIS', 120);
SET @a_BIS_IMD_DD := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_BIS_IMD_DD, 'TASK', 'IMD-DD-1', '업무과제별 개선모델 수립', 'BIS', 120);
SET @t_BIS_IMD_DD_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_BIS_IMD_DD, 'TASK', 'IMD-DD-2', 'IT과제별 개선모델 수립', 'BIS', 130);
SET @t_BIS_IMD_DD_2 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_BIS_IMD_DD, 'TASK', 'IMD-DD-3', '현업검증', 'BIS', 140);
SET @t_BIS_IMD_DD_3 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, description, methodology, sort_order) VALUES (NULL, 'PHASE', 'RMP', '실행계획수립 (RoadMap Plan)', NULL, 'BIS', 150);
SET @ph := LAST_INSERT_ID();
SET @p_BIS_RMP := @ph;
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@p_BIS_RMP, 'ACTIVITY', 'RMP-RP', '실행계획수립 (RoadMap Plan)', 'BIS', 150);
SET @a_BIS_RMP_RP := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_BIS_RMP_RP, 'TASK', 'RMP-RP-1', '통합이행 과제정의', 'BIS', 150);
SET @t_BIS_RMP_RP_1 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_BIS_RMP_RP, 'TASK', 'RMP-RP-2', '과제간 우선 순위 결정', 'BIS', 160);
SET @t_BIS_RMP_RP_2 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_BIS_RMP_RP, 'TASK', 'RMP-RP-3', '단계별 이행전략 수립', 'BIS', 170);
SET @t_BIS_RMP_RP_3 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_BIS_RMP_RP, 'TASK', 'RMP-RP-4', '기대효과 분석', 'BIS', 180);
SET @t_BIS_RMP_RP_4 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_BIS_RMP_RP, 'TASK', 'RMP-RP-5', '실행조직 수립', 'BIS', 190);
SET @t_BIS_RMP_RP_5 := LAST_INSERT_ID();
INSERT INTO pms_catalog_node (parent_node_id, node_type, code, name, methodology, sort_order) VALUES (@a_BIS_RMP_RP, 'TASK', 'RMP-RP-6', '변화관리방안 수립', 'BIS', 200);
SET @t_BIS_RMP_RP_6 := LAST_INSERT_ID();
-- BIS: PHASE 3 · ACTIVITY 5 · TASK 20 · DELIVERABLE 0
